// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zetas-current/Dashboard.tsx": () => import("../components/mockups/zetas-current/Dashboard.tsx"),
  "./components/mockups/zetas-current/OrderDetail.tsx": () => import("../components/mockups/zetas-current/OrderDetail.tsx"),
  "./components/mockups/zetas-current/Orders.tsx": () => import("../components/mockups/zetas-current/Orders.tsx")
};
